
import { Offer, Category, User, BannerItem } from './types';

export const mockUser: User = {
  id: 'user1',
  name: 'John Doe',
  email: 'john@example.com',
  phone: '+1234567890',
  location: 'India',
  savedOffers: ['1', '3', '5'],
  points: 1250
};

export const mockOffers: Offer[] = [
  {
    id: '1',
    title: '50% off on Nike Shoes',
    description: 'Get 50% off on all Nike shoes. Limited time offer.',
    imageUrl: '/nike-shoes.jpg',
    store: 'Nike',
    category: 'Fashion',
    price: 50,
    originalPrice: 100,
    expiryDate: '2024-07-30',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, New Delhi'
    },
    isAmazon: false,
    affiliateLink: 'https://example.com/nike-deal',
    terms: 'Terms and conditions apply.',
    savings: '50%',
    lmdId: 12345,
    merchantHomepage: 'https://nike.com',
    longOffer: 'This is a long description of the offer.',
    code: 'NIKE50',
    termsAndConditions: 'Offer valid on select items only.',
    featured: true,
    publisherExclusive: false,
    sponsored: true,
    url: 'https://example.com/nike-deal',
    smartlink: 'https://s.zlink.io/u/abcdef',
    offerType: 'Discount',
    offerValue: '50%',
    status: 'active',
    startDate: '2024-06-01',
    endDate: '2024-07-30',
    categories: 'Shoes, Fashion'
  },
  {
    id: '2',
    title: 'Buy One Get One Free on Pizza',
    description: 'Buy one pizza and get one free at Domino\'s.',
    imageUrl: '/dominos-pizza.jpg',
    store: 'Domino\'s',
    category: 'Food',
    price: 15,
    originalPrice: 15,
    expiryDate: '2024-07-15',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, New Delhi'
    },
    isAmazon: false,
    affiliateLink: 'https://example.com/dominos-bogo',
    terms: 'Valid on medium and large pizzas only.',
    savings: '50%',
    lmdId: 67890,
    merchantHomepage: 'https://dominos.com',
    longOffer: 'This is a long description of the offer.',
    code: 'BOGOPIZZA',
    termsAndConditions: 'Offer valid on select items only.',
    featured: false,
    publisherExclusive: true,
    sponsored: false,
    url: 'https://example.com/dominos-bogo',
    smartlink: 'https://s.zlink.io/u/ghijkl',
    offerType: 'BOGO',
    offerValue: '1 Free Pizza',
    status: 'active',
    startDate: '2024-06-01',
    endDate: '2024-07-15',
    categories: 'Pizza, Food'
  },
  {
    id: '3',
    title: '30% off on Electronics',
    description: 'Get 30% off on all electronics at Croma.',
    imageUrl: '/croma-electronics.jpg',
    store: 'Croma',
    category: 'Electronics',
    price: 200,
    originalPrice: 285.71,
    expiryDate: '2024-08-10',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, New Delhi'
    },
    isAmazon: false,
    affiliateLink: 'https://example.com/croma-deal',
    terms: 'Offer valid on select items only.',
    savings: '30%',
    lmdId: 24680,
    merchantHomepage: 'https://croma.com',
    longOffer: 'This is a long description of the offer.',
    code: 'CROMA30',
    termsAndConditions: 'Offer valid on select items only.',
    featured: true,
    publisherExclusive: false,
    sponsored: false,
    url: 'https://example.com/croma-deal',
    smartlink: 'https://s.zlink.io/u/mnopqr',
    offerType: 'Discount',
    offerValue: '30%',
    status: 'active',
    startDate: '2024-06-01',
    endDate: '2024-08-10',
    categories: 'Electronics'
  },
  {
    id: '4',
    title: '20% off on Fashion',
    description: 'Get 20% off on all fashion items at Myntra.',
    imageUrl: '/myntra-fashion.jpg',
    store: 'Myntra',
    category: 'Fashion',
    price: 40,
    originalPrice: 50,
    expiryDate: '2024-07-20',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, New Delhi'
    },
    isAmazon: false,
    affiliateLink: 'https://example.com/myntra-deal',
    terms: 'Offer valid on select items only.',
    savings: '20%',
    lmdId: 13579,
    merchantHomepage: 'https://myntra.com',
    longOffer: 'This is a long description of the offer.',
    code: 'MYNTRA20',
    termsAndConditions: 'Offer valid on select items only.',
    featured: false,
    publisherExclusive: true,
    sponsored: false,
    url: 'https://example.com/myntra-deal',
    smartlink: 'https://s.zlink.io/u/stuvwxyz',
    offerType: 'Discount',
    offerValue: '20%',
    status: 'active',
    startDate: '2024-06-01',
    endDate: '2024-07-20',
    categories: 'Fashion'
  },
  {
    id: '5',
    title: 'Free Shipping on Orders Above $50',
    description: 'Get free shipping on orders above $50 at Amazon.',
    imageUrl: '/amazon-shipping.jpg',
    store: 'Amazon',
    category: 'Miscellaneous',
    price: 0,
    originalPrice: 0,
    expiryDate: '2024-08-01',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, New Delhi'
    },
    isAmazon: true,
    affiliateLink: 'https://example.com/amazon-shipping',
    terms: 'Offer valid on select items only.',
    savings: 'Free',
    lmdId: 98765,
    merchantHomepage: 'https://amazon.com',
    longOffer: 'This is a long description of the offer.',
    code: 'FREESHIP',
    termsAndConditions: 'Offer valid on select items only.',
    featured: true,
    publisherExclusive: false,
    sponsored: true,
    url: 'https://example.com/amazon-shipping',
    smartlink: 'https://s.zlink.io/u/abcedf',
    offerType: 'Shipping',
    offerValue: 'Free',
    status: 'active',
    startDate: '2024-06-01',
    endDate: '2024-08-01',
    categories: 'Shipping'
  },
  {
    id: '6',
    title: '40% off on Hotel Bookings',
    description: 'Get 40% off on all hotel bookings at MakeMyTrip.',
    imageUrl: '/makemytrip-hotel.jpg',
    store: 'MakeMyTrip',
    category: 'Travel',
    price: 100,
    originalPrice: 166.67,
    expiryDate: '2024-07-25',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, New Delhi'
    },
    isAmazon: false,
    affiliateLink: 'https://example.com/makemytrip-deal',
    terms: 'Offer valid on select hotels only.',
    savings: '40%',
     lmdId: 54321,
    merchantHomepage: 'https://makemytrip.com',
    longOffer: 'This is a long description of the offer.',
    code: 'MMT40',
    termsAndConditions: 'Offer valid on select hotels only.',
    featured: false,
    publisherExclusive: true,
    sponsored: false,
    url: 'https://example.com/makemytrip-deal',
    smartlink: 'https://s.zlink.io/u/ghijklm',
    offerType: 'Discount',
    offerValue: '40%',
    status: 'active',
    startDate: '2024-06-01',
    endDate: '2024-07-25',
    categories: 'Hotels, Travel'
  },
  {
    id: '7',
    title: '25% off on Beauty Products',
    description: 'Get 25% off on all beauty products at Nykaa.',
    imageUrl: '/nykaa-beauty.jpg',
    store: 'Nykaa',
    category: 'Beauty',
    price: 30,
    originalPrice: 40,
    expiryDate: '2024-08-05',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, New Delhi'
    },
    isAmazon: false,
    affiliateLink: 'https://example.com/nykaa-deal',
    terms: 'Offer valid on select items only.',
    savings: '25%',
    lmdId: 78901,
    merchantHomepage: 'https://nykaa.com',
    longOffer: 'This is a long description of the offer.',
    code: 'NYKAA25',
    termsAndConditions: 'Offer valid on select items only.',
    featured: false,
    publisherExclusive: false,
    sponsored: false,
    url: 'https://example.com/nykaa-deal',
    smartlink: 'https://s.zlink.io/u/nopqrst',
    offerType: 'Discount',
    offerValue: '25%',
    status: 'active',
    startDate: '2024-06-01',
    endDate: '2024-08-05',
    categories: 'Beauty'
  },
  {
    id: '8',
    title: '10% off on Grocery',
    description: 'Get 10% off on all grocery items at BigBasket.',
    imageUrl: '/bigbasket-grocery.jpg',
    store: 'BigBasket',
    category: 'Grocery',
    price: 25,
    originalPrice: 27.78,
    expiryDate: '2024-07-31',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, New Delhi'
    },
    isAmazon: false,
    affiliateLink: 'https://example.com/bigbasket-deal',
    terms: 'Offer valid on select items only.',
    savings: '10%',
    lmdId: 36912,
    merchantHomepage: 'https://bigbasket.com',
    longOffer: 'This is a long description of the offer.',
    code: 'BB10',
    termsAndConditions: 'Offer valid on select items only.',
    featured: false,
    publisherExclusive: false,
    sponsored: false,
    url: 'https://example.com/bigbasket-deal',
    smartlink: 'https://s.zlink.io/u/uvwxyz',
    offerType: 'Discount',
    offerValue: '10%',
    status: 'active',
    startDate: '2024-06-01',
    endDate: '2024-07-31',
    categories: 'Grocery'
  },
  {
    id: '9',
    title: 'Free Movie Ticket with Food Combo',
    description: 'Get a free movie ticket with a food combo purchase at PVR Cinemas.',
    imageUrl: '/pvr-cinemas.jpg',
    store: 'PVR Cinemas',
    category: 'Entertainment',
    price: 30,
    originalPrice: 30,
    expiryDate: '2024-08-15',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, New Delhi'
    },
    isAmazon: false,
    affiliateLink: 'https://example.com/pvr-deal',
    terms: 'Offer valid on select combos only.',
    savings: 'Free Ticket',
    lmdId: 85203,
    merchantHomepage: 'https://pvrcinemas.com',
    longOffer: 'This is a long description of the offer.',
    code: 'PVRMOVIE',
    termsAndConditions: 'Offer valid on select combos only.',
    featured: false,
    publisherExclusive: false,
    sponsored: false,
    url: 'https://example.com/pvr-deal',
    smartlink: 'https://s.zlink.io/u/123456',
    offerType: 'Free Ticket',
    offerValue: '1 Movie Ticket',
    status: 'active',
    startDate: '2024-06-01',
    endDate: '2024-08-15',
    categories: 'Entertainment'
  },
  {
    id: '10',
    title: '60% off on Furniture',
    description: 'Get 60% off on all furniture at Pepperfry.',
    imageUrl: '/pepperfry-furniture.jpg',
    store: 'Pepperfry',
    category: 'Home & Furniture',
    price: 250,
    originalPrice: 625,
    expiryDate: '2024-07-28',
    location: {
      lat: 28.6139,
      lng: 77.2090,
      address: 'Connaught Place, New Delhi'
    },
    isAmazon: false,
    affiliateLink: 'https://example.com/pepperfry-deal',
    terms: 'Offer valid on select items only.',
    savings: '60%',
    lmdId: 47015,
    merchantHomepage: 'https://pepperfry.com',
    longOffer: 'This is a long description of the offer.',
    code: 'PEPPER60',
    termsAndConditions: 'Offer valid on select items only.',
    featured: false,
    publisherExclusive: false,
    sponsored: false,
    url: 'https://example.com/pepperfry-deal',
    smartlink: 'https://s.zlink.io/u/789012',
    offerType: 'Discount',
    offerValue: '60%',
    status: 'active',
    startDate: '2024-06-01',
    endDate: '2024-07-28',
    categories: 'Furniture, Home & Furniture'
  }
];

export const mockCategories: Category[] = [
  {
    id: 'fashion',
    name: 'Fashion',
    icon: '🛍️',
    subcategories: ['Men\'s Fashion', 'Women\'s Fashion', 'Kids\' Fashion']
  },
  {
    id: 'electronics',
    name: 'Electronics',
    icon: '📱',
    subcategories: ['Mobiles', 'Laptops', 'TVs', 'Audio']
  },
  {
    id: 'food',
    name: 'Food',
    icon: '🍔',
    subcategories: ['Restaurants', 'Fast Food', 'Delivery']
  },
  {
    id: 'travel',
    name: 'Travel',
    icon: '✈️',
    subcategories: ['Flights', 'Hotels', 'Vacation Packages']
  },
  {
    id: 'beauty',
    name: 'Beauty',
    icon: '💄',
    subcategories: ['Makeup', 'Skincare', 'Haircare']
  },
  {
    id: 'grocery',
    name: 'Grocery',
    icon: '🍎',
    subcategories: ['Fruits', 'Vegetables', 'Dairy', 'Snacks']
  },
  {
    id: 'home-furniture',
    name: 'Home & Furniture',
    icon: '🏠',
    subcategories: ['Furniture', 'Decor', 'Appliances']
  },
  {
    id: 'entertainment',
    name: 'Entertainment',
    icon: '🎬',
    subcategories: ['Movies', 'Music', 'Events']
  },
  {
    id: 'miscellaneous',
    name: 'Miscellaneous',
    icon: '🎁',
    subcategories: ['Books', 'Gifts', 'Stationery']
  }
];

export const mockBanners: BannerItem[] = [
  {
    id: 'banner1',
    imageUrl: '/banner1.jpg',
    title: 'Summer Sale',
    link: '/offers?category=fashion'
  },
  {
    id: 'banner2',
    imageUrl: '/banner2.jpg',
    title: 'Electronics Fest',
    link: '/offers?category=electronics'
  },
  {
    id: 'banner3',
    imageUrl: '/banner3.jpg',
    title: 'Food Offers',
    link: '/offers?category=food'
  }
];
