
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmqkvjxsxufozfgqjoxz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tcWt2anhzeHVmb3pmZ3Fqb3h6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc2NTA0NjYsImV4cCI6MjA2MzIyNjQ2Nn0.enK86qnUULCkOQhzVjsz68gTu3854tLwn1Y3Snah6f4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: typeof localStorage !== 'undefined' ? localStorage : undefined, 
    persistSession: true,
    autoRefreshToken: true,
  },
  db: {
    schema: 'public'
  },
  global: {
    headers: { 'x-my-custom-header': 'monkey-deals-app' },
    // Increase timeout for larger data sets and improve reliability
    fetch: (url, options) => {
      return fetch(url, {
        ...options,
        signal: AbortSignal.timeout(120000), // Increase to 2 minute timeout for larger datasets
      });
    }
  }
});
