
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://vtxtnyivbmvcmxuuqknn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0eHRueWl2Ym12Y214dXVxa25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTczMDcsImV4cCI6MjA2MzY3MzMwN30.MDY79onfEFsVP5hczJSQJspEZg4ie3HeJ9utbTsVWHA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create client with enhanced configuration for better session persistence
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  }
});
